In [16]:
import numpy as np    # 한번 import하고 나면 그 뒤는 안해도 됨
arr1 = np.arange(1, 10, 2)
print(arr1)

[1 3 5 7 9]


In [18]:
arr2 = np.ones((3, 4))

print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
arr3 = np.linspace(0, 1, 10)

print(arr3)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [33]:
# 1. A행렬을 생성해보자.
A = np.array([[ 1, 2, 3, 4, 5],
              [ 6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

# 2. A의 모양(shape)을 출력해보자.
print(A.shape)

# 3. 19 값을 추출해보자.
print(A[3, 3])

# 4. 슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자.
print(A[:2, :2])

# 5. 슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자.
print(A[-2:, -2:])

# 6. 슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자.
print(A[:2, :])

# 7. 슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자.
print(A[:, -2:])

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [37]:
# 1. A행렬을 생성해보자.
A = np.arange(1, 37)
AA = np.reshape(3, 4, 3)
print(AA)

# 2. A 배열의 모양과 크기를 출력해보자.
print(A.shape)
print(A.size)

# 3. A의 모양을 (3, 4, 3)로 변경해보자.
# 4. A를 1차원 배열로 구성해보자.

TypeError: order must be str, not int